# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift Education Task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
	pod 'EzImageLoader'
  # Pods for Swift Education Task

  target 'Swift Education TaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift Education TaskUITests' do
    # Pods for testing
  end

end
